In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Wine.csv')

In [3]:
df.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [4]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [6]:
ss = StandardScaler()
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [8]:
Y = ct.fit_transform(Y.reshape(len(Y),1))

In [11]:
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X,Y,test_size=0.2,random_state=0)

In [12]:
Xtrain = ss.fit_transform(Xtrain)
Xtest = ss.transform(Xtest)

In [13]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
Xtrain = pca.fit_transform(Xtrain)
Xtest = pca.fit_transform(Xtest)

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
classifierDTC = DecisionTreeClassifier(criterion='entropy',random_state=0)

In [16]:
classifierDTC.fit(Xtrain,Ytrain)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [17]:
Ypred_DTC = classifierDTC.predict(Xtest)

In [27]:
Ypred_DTC = np.argmax(Ypred_DTC,axis=1)

In [28]:
Ypred_DTC

array([0, 2, 1, 0, 1, 0, 0, 2, 1, 1, 2, 2, 0, 1, 2, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 2, 1, 1, 1, 2, 2, 0, 0, 2, 0, 0, 0])

In [25]:
Ytest = np.argmax(Ytest,axis=1)

In [26]:
Ytest

array([0, 2, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 0, 1, 2, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0])

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [29]:
cm = confusion_matrix(Ytest,Ypred_DTC)
print(f'confusion matrix :{cm}')
print(f'accuracy score :{accuracy_score(Ytest,Ypred_DTC)}')
print(f'classification report : {classification_report(Ytest,Ypred_DTC)}')

confusion matrix :[[13  1  0]
 [ 1 12  3]
 [ 0  0  6]]
accuracy score :0.8611111111111112
classification report :               precision    recall  f1-score   support

           0       0.93      0.93      0.93        14
           1       0.92      0.75      0.83        16
           2       0.67      1.00      0.80         6

    accuracy                           0.86        36
   macro avg       0.84      0.89      0.85        36
weighted avg       0.88      0.86      0.86        36

